/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminAuthedReviewRouteImport } from './routes/admin/_authed/review'
import { Route as AdminAuthedDashboardRouteImport } from './routes/admin/_authed/dashboard'
import { Route as AuthenticatedPlayerMatchesRouteImport } from './routes/_authenticated/player/matches'
import { Route as AuthenticatedPlayerDashboardRouteImport } from './routes/_authenticated/player/dashboard'
import { Route as AuthenticatedPlayerCareerStatsRouteImport } from './routes/_authenticated/player/career-stats'
import { Route as AuthenticatedOrgDashboardRouteImport } from './routes/_authenticated/org/dashboard'
import { Route as AdminAuthedSportsIndexRouteImport } from './routes/admin/_authed/sports.index'
import { Route as AdminAuthedSportsSportIdRouteImport } from './routes/admin/_authed/sports.$sportId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAuthedReviewRoute = AdminAuthedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDashboardRoute = AdminAuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AuthenticatedPlayerMatchesRoute =
  AuthenticatedPlayerMatchesRouteImport.update({
    id: '/player/matches',
    path: '/player/matches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayerDashboardRoute =
  AuthenticatedPlayerDashboardRouteImport.update({
    id: '/player/dashboard',
    path: '/player/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayerCareerStatsRoute =
  AuthenticatedPlayerCareerStatsRouteImport.update({
    id: '/player/career-stats',
    path: '/player/career-stats',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgDashboardRoute =
  AuthenticatedOrgDashboardRouteImport.update({
    id: '/org/dashboard',
    path: '/org/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAuthedSportsIndexRoute = AdminAuthedSportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedSportsSportIdRoute =
  AdminAuthedSportsSportIdRouteImport.update({
    id: '/sports/$sportId',
    path: '/sports/$sportId',
    getParentRoute: () => AdminAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/org/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/player/career-stats': typeof AuthenticatedPlayerCareerStatsRoute
  '/player/dashboard': typeof AuthenticatedPlayerDashboardRoute
  '/player/matches': typeof AuthenticatedPlayerMatchesRoute
  '/admin/dashboard': typeof AdminAuthedDashboardRoute
  '/admin/review': typeof AdminAuthedReviewRoute
  '/admin/sports/$sportId': typeof AdminAuthedSportsSportIdRoute
  '/admin/sports/': typeof AdminAuthedSportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/org/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/player/career-stats': typeof AuthenticatedPlayerCareerStatsRoute
  '/player/dashboard': typeof AuthenticatedPlayerDashboardRoute
  '/player/matches': typeof AuthenticatedPlayerMatchesRoute
  '/admin/dashboard': typeof AdminAuthedDashboardRoute
  '/admin/review': typeof AdminAuthedReviewRoute
  '/admin/sports/$sportId': typeof AdminAuthedSportsSportIdRoute
  '/admin/sports': typeof AdminAuthedSportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/org/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/_authenticated/player/career-stats': typeof AuthenticatedPlayerCareerStatsRoute
  '/_authenticated/player/dashboard': typeof AuthenticatedPlayerDashboardRoute
  '/_authenticated/player/matches': typeof AuthenticatedPlayerMatchesRoute
  '/admin/_authed/dashboard': typeof AdminAuthedDashboardRoute
  '/admin/_authed/review': typeof AdminAuthedReviewRoute
  '/admin/_authed/sports/$sportId': typeof AdminAuthedSportsSportIdRoute
  '/admin/_authed/sports/': typeof AdminAuthedSportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/dashboard'
    | '/admin'
    | '/admin/login'
    | '/org/dashboard'
    | '/player/career-stats'
    | '/player/dashboard'
    | '/player/matches'
    | '/admin/dashboard'
    | '/admin/review'
    | '/admin/sports/$sportId'
    | '/admin/sports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/dashboard'
    | '/admin'
    | '/admin/login'
    | '/org/dashboard'
    | '/player/career-stats'
    | '/player/dashboard'
    | '/player/matches'
    | '/admin/dashboard'
    | '/admin/review'
    | '/admin/sports/$sportId'
    | '/admin/sports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/_authenticated/dashboard'
    | '/admin/_authed'
    | '/admin/login'
    | '/_authenticated/org/dashboard'
    | '/_authenticated/player/career-stats'
    | '/_authenticated/player/dashboard'
    | '/_authenticated/player/matches'
    | '/admin/_authed/dashboard'
    | '/admin/_authed/review'
    | '/admin/_authed/sports/$sportId'
    | '/admin/_authed/sports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/_authed/review': {
      id: '/admin/_authed/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminAuthedReviewRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dashboard': {
      id: '/admin/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthedDashboardRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/_authenticated/player/matches': {
      id: '/_authenticated/player/matches'
      path: '/player/matches'
      fullPath: '/player/matches'
      preLoaderRoute: typeof AuthenticatedPlayerMatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/player/dashboard': {
      id: '/_authenticated/player/dashboard'
      path: '/player/dashboard'
      fullPath: '/player/dashboard'
      preLoaderRoute: typeof AuthenticatedPlayerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/player/career-stats': {
      id: '/_authenticated/player/career-stats'
      path: '/player/career-stats'
      fullPath: '/player/career-stats'
      preLoaderRoute: typeof AuthenticatedPlayerCareerStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org/dashboard': {
      id: '/_authenticated/org/dashboard'
      path: '/org/dashboard'
      fullPath: '/org/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/_authed/sports/': {
      id: '/admin/_authed/sports/'
      path: '/sports'
      fullPath: '/admin/sports/'
      preLoaderRoute: typeof AdminAuthedSportsIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/sports/$sportId': {
      id: '/admin/_authed/sports/$sportId'
      path: '/sports/$sportId'
      fullPath: '/admin/sports/$sportId'
      preLoaderRoute: typeof AdminAuthedSportsSportIdRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrgDashboardRoute: typeof AuthenticatedOrgDashboardRoute
  AuthenticatedPlayerCareerStatsRoute: typeof AuthenticatedPlayerCareerStatsRoute
  AuthenticatedPlayerDashboardRoute: typeof AuthenticatedPlayerDashboardRoute
  AuthenticatedPlayerMatchesRoute: typeof AuthenticatedPlayerMatchesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrgDashboardRoute: AuthenticatedOrgDashboardRoute,
  AuthenticatedPlayerCareerStatsRoute: AuthenticatedPlayerCareerStatsRoute,
  AuthenticatedPlayerDashboardRoute: AuthenticatedPlayerDashboardRoute,
  AuthenticatedPlayerMatchesRoute: AuthenticatedPlayerMatchesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminAuthedRouteChildren {
  AdminAuthedDashboardRoute: typeof AdminAuthedDashboardRoute
  AdminAuthedReviewRoute: typeof AdminAuthedReviewRoute
  AdminAuthedSportsSportIdRoute: typeof AdminAuthedSportsSportIdRoute
  AdminAuthedSportsIndexRoute: typeof AdminAuthedSportsIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedDashboardRoute: AdminAuthedDashboardRoute,
  AdminAuthedReviewRoute: AdminAuthedReviewRoute,
  AdminAuthedSportsSportIdRoute: AdminAuthedSportsSportIdRoute,
  AdminAuthedSportsIndexRoute: AdminAuthedSportsIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
